app.ldap.url=${LDAP_URL:ldap://localhost:8389}
app.ldap.base=${LDAP_BASE:dc=example,dc=com}
app.ldap.user-dn-pattern=${LDAP_USER_DN_PATTERN:uid={0},ou=people}
app.ldap.group-search-base=${LDAP_GROUP_SEARCH_BASE:ou=groups}
app.ldap.manager-dn=${LDAP_MANAGER_DN:cn=admin,dc=example,dc=com}
app.ldap.manager-password=${LDAP_MANAGER_PASSWORD:admin}
app.ldap.hr-group=${LDAP_HR_GROUP:hr}
app.ldap.interviewer-group=${LDAP_INTERVIEWER_GROUP:interviewers}
app.ldap.admin-group=${LDAP_ADMIN_GROUP:admins}
